<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><NoWarn>$(NoWarn);xUnit1051</NoWarn><RootNamespace>NFour.AutoUpdater.Client.Tests</RootNamespace></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/NFour.AutoUpdater.Client/NFour.AutoUpdater.Client.csproj" /><ProjectReference Include="../../src/NFour.AutoUpdater.Core/NFour.AutoUpdater.Core.csproj" /><ProjectReference Include="../../src/NFour.AutoUpdater.Storage.Memory/NFour.AutoUpdater.Storage.Memory.csproj" /><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit.v3" /><PackageReference Include="xunit.runner.visualstudio" /></ItemGroup>
</Project>
