<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><NoWarn>$(NoWarn);xUnit1051</NoWarn><RootNamespace>FourSaas.AutoUpdater.Storage.S3.Tests</RootNamespace></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/FourSaas.AutoUpdater.Storage.S3/FourSaas.AutoUpdater.Storage.S3.csproj" /><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit.v3" /><PackageReference Include="xunit.runner.visualstudio" /></ItemGroup>
</Project>
