using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FourSaas.AutoUpdater.Server.Migrations;

/// <summary>
/// Converts telemetry to a time-partitioned append-only table. The default
/// partition keeps deployments operational until their retention job creates
/// bounded monthly partitions; old partitions can then be detached/dropped
/// without scanning the control-plane tables.
/// </summary>
[Migration("20260805200000_TelemetryPartitioning")]
public partial class TelemetryPartitioning : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DO $$
            BEGIN
                IF to_regclass('"Telemetry"') IS NOT NULL AND to_regclass('"Telemetry_legacy"') IS NULL THEN
                    ALTER TABLE "Telemetry" RENAME TO "Telemetry_legacy";
                    CREATE TABLE "Telemetry" (
                        "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "At" timestamp with time zone NOT NULL,
                        "ProductId" text NULL,
                        "ReleaseId" text NULL,
                        "PayloadJson" text NULL,
                        CONSTRAINT "PK_Telemetry" PRIMARY KEY ("Id", "At")
                    ) PARTITION BY RANGE ("At");
                    CREATE TABLE "Telemetry_default" PARTITION OF "Telemetry" DEFAULT;
                    INSERT INTO "Telemetry" ("Id", "At", "ProductId", "ReleaseId", "PayloadJson")
                        SELECT "Id", "At", "ProductId", "ReleaseId", "PayloadJson" FROM "Telemetry_legacy";
                    PERFORM setval(pg_get_serial_sequence('"Telemetry"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Telemetry"), 1), (SELECT COUNT(*) > 0 FROM "Telemetry"));
                    DROP TABLE "Telemetry_legacy";
                    CREATE INDEX "IX_Telemetry_At" ON "Telemetry" ("At");
                    COMMENT ON TABLE "Telemetry" IS 'Partition by UTC month and retain according to the deployment telemetry-retention policy.';
                END IF;
            END $$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DO $$
            BEGIN
                IF to_regclass('"Telemetry"') IS NOT NULL AND to_regclass('"Telemetry_legacy"') IS NULL THEN
                    ALTER TABLE "Telemetry" RENAME TO "Telemetry_partitioned";
                    CREATE TABLE "Telemetry" (
                        "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        "At" timestamp with time zone NOT NULL,
                        "ProductId" text NULL,
                        "ReleaseId" text NULL,
                        "PayloadJson" text NULL,
                        CONSTRAINT "PK_Telemetry" PRIMARY KEY ("Id")
                    );
                    INSERT INTO "Telemetry" ("Id", "At", "ProductId", "ReleaseId", "PayloadJson")
                        SELECT "Id", "At", "ProductId", "ReleaseId", "PayloadJson" FROM "Telemetry_partitioned";
                    DROP TABLE "Telemetry_partitioned" CASCADE;
                    CREATE INDEX "IX_Telemetry_At" ON "Telemetry" ("At");
                END IF;
            END $$;
            """);
    }
}
