// <auto-generated />
using System;
using FourSaas.AutoUpdater.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FourSaas.AutoUpdater.Server.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    partial class ManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.AuditEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.BlobPlacementRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("Algorithm")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("BackendId")
                        .HasColumnType("text");

                    b.Property<string>("ObjectKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepositoryId", "Algorithm", "Hash", "BackendId", "ObjectKey");

                    b.HasIndex("RepositoryId", "Algorithm", "Hash", "VerifiedAt");

                    b.ToTable("BlobPlacements");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.BlobRefRow", b =>
                {
                    b.Property<string>("Algorithm")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("Algorithm", "Hash");

                    b.ToTable("BlobRefs");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.ChannelRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<long>("ChannelSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("PointerDigest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RepositoryId", "ProductId", "Channel");

                    b.HasIndex("RepositoryId", "ProductId", "Channel", "ChannelSequence")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.PackageVersionRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<string>("FileTableJson")
                        .HasColumnType("text");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("WhenJson")
                        .HasColumnType("jsonb");

                    b.HasKey("RepositoryId", "PackageId", "Version");

                    b.HasIndex("WhenJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WhenJson"), "gin");

                    b.HasIndex("RepositoryId", "PackageId", "Sequence")
                        .IsUnique();

                    b.ToTable("PackageVersions");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.ProductRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepositoryId", "ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.PublishGrantRow", b =>
                {
                    b.Property<string>("GrantId")
                        .HasColumnType("text");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StagingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MultipartUploadId")
                        .HasColumnType("text");

                    b.Property<long?>("MultipartPartSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("MultipartCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MultipartCompleting")
                        .HasColumnType("boolean");

                    b.Property<string>("MultipartPartsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("GrantId");

                    b.ToTable("PublishGrants");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.PublishSessionRow", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxObjects")
                        .HasColumnType("integer");

                    b.Property<long>("MaxTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ObjectCount")
                        .HasColumnType("integer");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sealed")
                        .HasColumnType("boolean");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("SessionId");

                    b.ToTable("PublishSessions");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.ReleaseDraftRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("DraftId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RepositoryId", "DraftId");

                    b.HasIndex("PayloadJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PayloadJson"), "gin");

                    b.ToTable("ReleaseDrafts");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.ReleaseRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseId")
                        .HasColumnType("text");

                    b.Property<string>("CoverageDigest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnvelopeDigest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("RepositoryId", "ProductId", "ReleaseId");

                    b.HasIndex("RepositoryId", "ProductId", "Sequence")
                        .IsUnique();

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.RevocationRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepositoryId", "ProductId");

                    b.ToTable("Revocations");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.TelemetryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseId")
                        .HasColumnType("text");

                    b.HasKey("Id", "At");

                    b.HasIndex("At");

                    b.ToTable("Telemetry");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.TrustedKeyRow", b =>
                {
                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.Property<string>("KeyId")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepositoryId", "KeyId");

                    b.ToTable("TrustedKeys");
                });

            modelBuilder.Entity("FourSaas.AutoUpdater.Server.SequenceReservationRow", b =>
                {
                    b.Property<string>("RepositoryId").HasColumnType("text");
                    b.Property<string>("Scope").HasColumnType("text");
                    b.Property<string>("Name").HasColumnType("text");
                    b.Property<long>("NextValue").HasColumnType("bigint");
                    b.Property<string>("AllocatedSequencesJson").HasColumnType("jsonb");
                    b.HasKey("RepositoryId", "Scope", "Name");
                    b.ToTable("SequenceReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
