global using System.Collections.Immutable;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using FourSaas.AutoUpdater.Core;
global using FourSaas.AutoUpdater.Repository;
global using FourSaas.AutoUpdater.Storage;
