<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>FourSaas.AutoUpdater.Cli</RootNamespace><AssemblyName>4sup</AssemblyName><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../FourSaas.AutoUpdater.Core/FourSaas.AutoUpdater.Core.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Client/FourSaas.AutoUpdater.Client.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Repository/FourSaas.AutoUpdater.Repository.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Publishing/FourSaas.AutoUpdater.Publishing.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Storage.Local/FourSaas.AutoUpdater.Storage.Local.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Storage.Http/FourSaas.AutoUpdater.Storage.Http.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Storage.S3/FourSaas.AutoUpdater.Storage.S3.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Storage.Ftp/FourSaas.AutoUpdater.Storage.Ftp.csproj" /><ProjectReference Include="../FourSaas.AutoUpdater.Storage.Brokering/FourSaas.AutoUpdater.Storage.Brokering.csproj" /></ItemGroup>
</Project>
