<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>NFour.AutoUpdater.Cli</RootNamespace><AssemblyName>4sup</AssemblyName><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../NFour.AutoUpdater.Core/NFour.AutoUpdater.Core.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Client/NFour.AutoUpdater.Client.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Repository/NFour.AutoUpdater.Repository.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Publishing/NFour.AutoUpdater.Publishing.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Storage.Local/NFour.AutoUpdater.Storage.Local.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Storage.Http/NFour.AutoUpdater.Storage.Http.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Storage.S3/NFour.AutoUpdater.Storage.S3.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Storage.Ftp/NFour.AutoUpdater.Storage.Ftp.csproj" /><ProjectReference Include="../NFour.AutoUpdater.Storage.Brokering/NFour.AutoUpdater.Storage.Brokering.csproj" /></ItemGroup>
</Project>
