<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FourSaas.AutoUpdater.Core</RootNamespace>
    <AssemblyName>FourSaas.AutoUpdater.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="BouncyCastle.Cryptography" />
  </ItemGroup>
</Project>
